#
# Playbook to update apache after updates to website
#
- hosts: chsservers
  remote_user: jenkins
  tasks:
    - name: Copy html web pages and content to apache directory
      copy:
        src: "{{ item }}"
        dest: /var/www/html
      with_fileglob: 
        - "sixthgrade.html"
        - "seventhandeighthgrade.html"
        - "nineandtenyearold.html"
        - "facilities.html"
        - "freshman.html"
        - "index.html"
        - "news.html"
        - "schedule.html"
        - "seasonticket.html"
        - "sponsors.html"
        - "self-service.html"
        - "swag.html"
        - "varsity.html"
        - "management.html"
      become: yes
      become_user: root
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "{{ item }}"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "navbar"
        marker_end: "navbarend"
        insertafter: "<body>"
        block: "{{ lookup('file', 'shared_components/navbar.html') }}"
      with_items:
        - /var/www/html/sixthgrade.html
        - /var/www/html/seventhandeighthgrade.html
        - /var/www/html/nineandtenyearold.html
        - /var/www/html/facilities.html
        - /var/www/html/freshman.html
        - /var/www/html/index.html
        - /var/www/html/news.html
        - /var/www/html/schedule.html
        - /var/www/html/seasonticket.html
        - /var/www/html/sponsors.html
        - /var/www/html/swag.html
        - /var/www/html/varsity.html
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /var/www/html/staticman/varsity/
        patterns: 'schedule-*.json'
      register: varsityschedule
    - name: Get latest file
      set_fact:
        varsityschedulefile: "{{ varsityschedule.files | sort(attribute='mtime',reverse=true) | first }}"
    - name: debug
      debug:
        msg: "{{varsityschedulefile}}"
    - name: Read JSON file (can also be a variable).
      shell: "cat {{varsityschedulefile.path}}"
      register: varsityschedulejson
    - name: Get foo value.
      set_fact:
        varsityschedule: "{{ (varsityschedulejson.stdout | from_json).data }}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "varsityschedule"
        marker_end: "varsityscheduleend"
        insertafter: "<!-- begin Varsity Schedule-->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{varsityschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/schedule.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "varsityschedule"
        marker_end: "varsityscheduleend"
        insertafter: "<!-- begin Varsity Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{varsityschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/varsity.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "varsityschedule"
        marker_end: "varsityscheduleend"
        insertafter: "<!-- begin Varsity Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{varsityschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "varsityscheduleonpage"
        marker_end: "varsityscheduleendonpage"
        insertafter: "<!-- begin Varsity Schedule on page-->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{varsityschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thepast"
        marker_end: "thepastend"
        insertafter: "<h2>The Past</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thepast.txt') }} </p>"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thepresent"
        marker_end: "thepresentend"
        insertafter: "<h2>The Present</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thepresent.txt') }} </p>"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thefuture"
        marker_end: "thefutureend"
        insertafter: "<h2>The Future</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thefuture.txt') }} </p>"
    - name: Read users from CSV file and return a dictionary
      read_csv:
        path: shared_components/primary_news.csv
      register: primarynews
      delegate_to: localhost
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Title}}-->"
        marker_begin: "primarynews"
        marker_end: "primarynewsend"
        insertafter: '<div class=\"row mb-2\">'
        block: "<div class=\"col-md-6\">
    <div class=\"card flex-md-row mb-4 box-shadow h-md-250\">
        <div class=\"card-body d-flex flex-column align-items-start\">
            <strong class=\"d-inline-block mb-2 text-primary\">{{item.Title}}</strong>
            <h3 class=\"mb-0\">
                <a class=\"text-light\" href=\"#\">{{item.WhattoDo}}</a>
            </h3>
            <div class=\"mb-1 text-sm\">{{item.Date}}</div>
            <div class=\"row\">
                <div class=\"col-md-12\">
                    <p class=\"card-text mb-auto\">{{item.DrivetoAction}}
                        <br><a class=\"btn btn-primary\" href=\"{{item.ActionLink}}\"> {{item.ActionDescription}} </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>"
      with_items: "{{primarynews.list}}"
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /var/www/html/staticman/varsity/
        patterns: 'coaches-*.json'
      register: varsitycoaches
    - name: Get latest file
      set_fact:
        varsitycoachesfile: "{{ varsitycoaches.files | sort(attribute='mtime',reverse=true) | first }}"
    - name: debug
      debug:
        msg: "{{varsitycoachesfile}}"
    - name: Read JSON file (can also be a variable).
      shell: "cat {{varsitycoachesfile.path}}"
      register: varsitycoachesjson
    - name: Get foo value.
      set_fact:
        varsitycoaches: "{{ (varsitycoachesjson.stdout | from_json).data }}"
    - name: debug
      debug:
        msg: "{{varsitycoaches}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/varsity.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.name}}-->"
        marker_begin: "varsitycoaches"
        marker_end: "varsitycoachesend"
        insertafter: '<!-- Begin Coach Bios-->'
        block: "<div class=\"row featurette\">
          <div class=\"col-md-7 order-md-1 order-2\">
            <h2 class=\"featurette-heading pl-3 \">{{item.name}}
            <br><span class=\"text-muted\">{{item.title}}</span></h2>
            <p class=\"lead pl-3\">{{item.bio}}</p>
          </div>
          <div class=\"col-md-4 ml-3 order-md-2 order-1\">
            <div class=\"column\">
              <div class=\"row\">
            <img class=\"img-fluid mx-auto img-thumbnail\"  style=\"max-width:225px; max-height:225px;\" src=\"{{item.imagelocation}}\" alt=\"Generic placeholder image\">
            </div>
          </div></div>
        </div>"
      with_items: "{{varsitycoaches}}"
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /var/www/html/staticman/freshman/
        patterns: 'coaches-*.json'
      register: freshmancoaches
    - name: Get latest file
      set_fact:
        freshmancoachesfile: "{{ freshmancoaches.files | sort(attribute='mtime',reverse=true) | first }}"
    - name: debug
      debug:
        msg: "{{freshmancoachesfile}}"
    - name: Read JSON file (can also be a variable).
      shell: "cat {{freshmancoachesfile.path}}"
      register: freshmancoachesjson
    - name: Get foo value.
      set_fact:
        freshmencoaches: "{{ (freshmancoachesjson.stdout | from_json).data }}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/freshman.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.name}}-->"
        marker_begin: "freshmencoaches"
        marker_end: "freshmencoachesend"
        insertafter: '<!-- Begin Coach Bios-->'
        block: "<div class=\"row featurette\">
          <div class=\"col-md-7 order-md-1 order-2\">
            <h2 class=\"featurette-heading pl-3 \">{{item.name}}
            <br><span class=\"text-muted\">{{item.title}}</span></h2>
            <p class=\"lead pl-3\">{{item.bio}}</p>
          </div>
          <div class=\"col-md-4 ml-3 order-md-2 order-1\">
            <div class=\"column\">
              <div class=\"row\">
            <img class=\"img-fluid mx-auto img-thumbnail\"  style=\"max-width:225px; max-height:225px;\" src=\"{{item.imagelocation}}\" alt=\"Generic placeholder image\">
            </div>
          </div></div>
        </div>"
      with_items: "{{freshmencoaches}}"
    - name: Read users from CSV file and return a dictionary
      read_csv:
        delimiter: ","
        path: shared_components/sixthgradecoaches.csv
      register: sixthgradecoaches
      delegate_to: localhost
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/sixthgrade.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.name}}-->"
        marker_begin: "somecoachstart"
        marker_end: "somecoachesend"
        insertafter: '<!-- Begin Coach Bios-->'
        block: "<div class=\"row featurette\">
          <div class=\"col-md-7 order-md-1 order-2\">
            <h2 class=\"featurette-heading pl-3 \">{{item.name}}
            <br><span class=\"text-muted\">{{item.title}}</span></h2>
            <p class=\"lead pl-3\">{{item.bio}}</p>
          </div>
          <div class=\"col-md-4 ml-3 order-md-2 order-1\">
            <div class=\"column\">
              <div class=\"row\">
            <img class=\"img-fluid mx-auto img-thumbnail\" style=\"max-width:225px; max-height:225px;\"  src=\"{{item.imagelocation}}\" alt=\"Generic placeholder image\">
            </div>
          </div></div>
        </div>"
      with_items: "{{sixthgradecoaches.list}}"
    - name: Read users from CSV file and return a dictionary
      read_csv:
        delimiter: ","
        path: shared_components/seventhandeighthcoaches.csv
      register: seventhandeighthcoaches
      delegate_to: localhost
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/seventhandeighthgrade.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.name}}-->"
        marker_begin: "seventhandeighthcoaches"
        marker_end: "seventhandeighthcoachesend"
        insertafter: '<!-- Begin Coach Bios-->'
        block: "<div class=\"row featurette\">
          <div class=\"col-md-7 order-md-1 order-2\">
            <h2 class=\"featurette-heading pl-3 \">{{item.name}}
            <br><span class=\"text-muted\">{{item.title}}</span></h2>
            <p class=\"lead pl-3\">{{item.bio}}</p>
          </div>
          <div class=\"col-md-4 ml-3 order-md-2 order-1\">
            <div class=\"column\">
              <div class=\"row\">
            <img class=\"img-fluid mx-auto img-thumbnail\"  style=\"max-width:225px; max-height:225px;\" src=\"{{item.imagelocation}}\" alt=\"Generic placeholder image\">
            </div>
          </div></div>
        </div>"
      with_items: "{{seventhandeighthcoaches.list}}"
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /var/www/html/staticman/nineandten/
        patterns: 'coaches-*.json'
      register: nineandtencoaches
    - name: Get latest file
      set_fact:
        nineandtencoachesfile: "{{ nineandtencoaches.files | sort(attribute='mtime',reverse=true) | first }}"
    - name: debug
      debug:
        msg: "{{nineandtencoachesfile}}"
    - name: Read JSON file (can also be a variable).
      shell: "cat {{nineandtencoachesfile.path}}"
      register: nineandtenyearoldscoaches
    - name: Get foo value.
      set_fact:
        nineandtencoachesjsondata: "{{ (nineandtenyearoldscoaches.stdout | from_json).data }}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/nineandtenyearold.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.name}}-->"
        marker_begin: "nineandtenyearoldscoaches"
        marker_end: "nineandtenyearoldscoachesend"
        insertafter: '<!-- Begin Coach Bios-->'
        block: "<div class=\"row featurette\">
          <div class=\"col-md-7 order-md-1 order-2\">
            <h2 class=\"featurette-heading pl-3 \">{{item.name}}
            <br><span class=\"text-muted\">{{item.title}}</span></h2>
            <p class=\"lead pl-3\">{{item.bio}}</p>
          </div>
          <div class=\"col-md-4 ml-3 order-md-2 order-1\">
            <div class=\"column\">
              <div class=\"row\">
            <img class=\"img-fluid mx-auto img-thumbnail\"  style=\"max-width:225px; max-height:225px;\" src=\"{{item.imagelocation}}\" alt=\"Generic placeholder image\">
            </div>
          </div></div>
        </div>"
      with_items: "{{nineandtencoachesjsondata}}"
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /var/www/html/staticman/freshman/
        patterns: 'schedule-*.json'
      register: freshmanschedule
    - name: Get latest file
      set_fact:
        freshmanschedulefile: "{{ freshmanschedule.files | sort(attribute='mtime',reverse=true) | first }}"
    - name: debug
      debug:
        msg: "{{freshmanschedulefile}}"
    - name: Read JSON file (can also be a variable).
      shell: "cat {{freshmanschedulefile.path}}"
      register: freshmanschedulejson
    - name: Get foo value.
      set_fact:
        freshmenschedule: "{{ (freshmanschedulejson.stdout | from_json).data }}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/freshman.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "freshmenscheduleschedule"
        marker_end: "freshmenschedulescheduleend"
        insertafter: "<!-- begin Freshman Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{freshmenschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/varsity.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "freshmenscheduleschedule"
        marker_end: "freshmenschedulescheduleend"
        insertafter: "<!-- begin Freshman Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{freshmenschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/schedule.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "freshmenscheduleschedule"
        marker_end: "freshmenschedulescheduleend"
        insertafter: "<!-- begin Freshman Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{freshmenschedule}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/schedule.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "jvscheduleschedule"
        marker_end: "jvschedulescheduleend"
        insertafter: "<!-- begin JV Schedule -->"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{freshmenschedule}}"
    - name: Read users from CSV file and return a dictionary
      command: "ls shared_components"
      register: shared_components_out
      delegate_to: localhost
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      become: yes
      become_user: root
      blockinfile:
        path: "/var/www/html/self-service.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item}}-->"
        marker_begin: "selfservicebegin"
        marker_end: "selfserviceend"
        insertafter: "<!-- Begin Management things-->"
        block: "<li class=\"list-item\">  <a href=\"shared_components\\{{item}}\" target=\"_blank\">{{item}}</a> </li>"
      with_items: "{{shared_components_out.stdout_lines}}"
