#
# Playbook to update apache after updates to website
#
- hosts: localhost
  tasks:
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "{{ item }}"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "navbar"
        marker_end: "navbarend"
        insertafter: "<body>"
        block: "{{ lookup('file', 'shared_components/navbar.html') }}"
      with_fileglob:
        - "6thgrade.html"
        - "7thand8thgrade.html"
        - "9and10yearold.html"
        - "facilities.html"
        - "freshman.html"
        - "index.html"
        - "news.html"
        - "schedule.html"
        - "seasonticket.html"
        - "sponsors.html"
        - "swag.html"
        - "varsity.html"
    - name: Read users from CSV file and return a dictionary
      read_csv:
        path: shared_components/varsity_schedule.csv
      register: varsityschedule
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Date}}-->"
        marker_begin: "varsityschedule"
        marker_end: "varsityscheduleend"
        insertbefore: "</tbody>"
        block: "<tr>
									<td>{{item.Date}}</td>
									<td>{{item.Time}}</td>
									<td>{{item.Location}}</td>
								</tr>"
      with_items: "{{varsityschedule.list}}"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thepast"
        marker_end: "thepastend"
        insertafter: "<h2>The Past</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thepast.txt') }} </p>"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thepresent"
        marker_end: "thepresentend"
        insertafter: "<h2>The Present</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thepresent.txt') }} </p>"
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        marker_begin: "thefuture"
        marker_end: "thefutureend"
        insertafter: "<h2>The Future</h2>"
        block: " <p> {{ lookup('file', 'shared_components/thefuture.txt') }} </p>"
    - name: Read users from CSV file and return a dictionary
      read_csv:
        path: shared_components/primary_news.csv
      register: primarynews
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      blockinfile:
        path: "index.html"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{item.Title}}-->"
        marker_begin: "primarynews"
        marker_end: "primarynewsend"
        insertafter: '<div class=\"row mb-2\">'
        block: "<div class=\"col-md-6\">
    <div class=\"card flex-md-row mb-4 box-shadow h-md-250\">
        <div class=\"card-body d-flex flex-column align-items-start\">
            <strong class=\"d-inline-block mb-2 text-primary\">{{item.Title}}</strong>
            <h3 class=\"mb-0\">
                <a class=\"text-light\" href=\"#\">{{item.WhattoDo}}</a>
            </h3>
            <div class=\"mb-1 text-sm\">{{item.Date}}</div>
            <div class=\"row\">
                <div class=\"col-md-12\">
                    <p class=\"card-text mb-auto\">{{item.DrivetoAction}}
                        <br><a class=\"btn btn-primary\" href=\"{{item.ActionLink}}\"> {{item.ActionDescription}} </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>"
      with_items: "{{primarynews.list}}"
