#
# Playbook to update apache after updates to website
#
- hosts: chsservers
  remote_user: jenkins
  become: yes
  become_user: root
  tasks:
      - name: Copy html web pages and content to apache directory
      copy:
        src: "{{ item }}"
        dest: /var/www/html
      with_items: 
        - ~*.html
    - name: Copy html web pages and content to apache directory
      copy:
        src: css/
        dest: /var/www/html/css/
    - name: Copy html web pages and content to apache directory
      copy:
        src: assets/
        dest: /var/www/html/assets/
    - name: Copy html web pages and content to apache directory
      copy:
        src: compiled/
        dest: /var/www/html/compiled/
    - name: Copy html web pages and content to apache directory
      copy:
        src: imgs/
        dest: /var/www/html/imgs/
    - name: Copy html web pages and content to apache directory
      copy:
        src: js/
        dest: /var/www/html/js/
